### ISSUE TITLE
`www.es.pycon.org` redirecciona a 2020

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/pycones2021-web#19]
Prueba: http://www.es.pycon.org

**Comment by sdelquin** [comment]
Friendly reminder @dukebody

**Comment by dukebody** [comment]
He eliminado el registro www.es.pycon.org que apuntaba a 176.9.11.11, un servidor fuera de nuestro control. Así solamente tenemos que mantener la redirección de es.pycon.org que está en https://github.com/python-spain/es.pycon.org-redirect.
