### ISSUE TITLE
Quitar dos caracteres raros

### ISSUE THREAD

**Issue by fergunet** [python-spain/pycones2021-web#41]
En algún momento al hacer merge han aparecido dos caracteres no ascii, uno en https://github.com/python-spain/pycones2021-web/blob/038e004ed58de9873a5927e8bfadd7fe95de5590/index.html#L2391 y el otro 3 líneas después (se ve a simple vista). Para no liarla yo mientras @sdelquin está trabajando añadiendo ponentes, te importa, Sergio, quitar estos caracteres cuando hagas el próximo commit y así es menos follón?

Un saludico!

**Comment by sdelquin** [comment]
Hola Pablo. Yo me encargo sin problema, pero no sé a qué caracteres te refieres 🤔

**Comment by fergunet** [comment]
Estos dos que salen en el código:
![imagen](https://user-images.githubusercontent.com/3056690/133003561-7f9d48f2-a99c-4959-8383-68490c18199b.png)

También se ven en la web:
![imagen](https://user-images.githubusercontent.com/3056690/133003610-158572c6-4169-4c05-a903-3d2bec677d4d.png)

No sé si será cosa de mi navegador o qué: a mi me salen en Github y la web online. A lo mejor si lo abres con tu editor están invisibles o algo, pero algo chungo está por ahí :P

**Comment by sdelquin** [comment]
Yo no lo veo ni en la web, ni en GitHub, ni con VSCode ni con vim 😅 
Así que no sé cómo ayudar 🤷🏻‍♂️  jeje

**Comment by fergunet** [comment]
Vale, es que en Chrome no se ve XD Y en Github web se ve solo en el firefox de Windows y no en el de Mac y Linux, qué paranoia. De todas maneras lo quito yo ahora.
