### ISSUE TITLE
Logo de 4Geeks Academy

### ISSUE THREAD

**Issue by sdelquin** [python-spain/pycones2021-web#42]
No se visualiza correctamente el logo de 4Geeks Academy en la sección de Sponsors:
![image](https://user-images.githubusercontent.com/1591599/133002231-0977d352-9aee-43c9-b037-10e00fad55ad.png)

**Comment by cmaureir** [comment]
El logo no existe en el repo :S

**Comment by sdelquin** [comment]
https://coursereport-s3-production.global.ssl.fastly.net/uploads/school/logo/260/original/4g-logo-negro-01.png
