### ISSUE TITLE
Campo url en ficheros .csv

### ISSUE THREAD

**Issue by sdelquin** [python-spain/pycones2021-web#44]
¿El campo `url` que aparece en `charlas.csv` y `talleres.csv` está pensado para que vaya a la cuenta de twitter del ponente?

**Comment by cmaureir** [comment]
No, es solo la URL relacionada a la charla, como repo git, sitio del proyecto, etc. El campo 'twitter' es el que faltaba pero lo agregué en https://github.com/python-spain/pycones2021-web/pull/49
