### ISSUE TITLE
Cambios en agenda

### ISSUE THREAD

**Issue by sdelquin** [python-spain/pycones2021-web#56]
Primer cambio confirmado:

Charla | Horario | Bloque
-- | -- | --
Desarrollo dirigido por modelos, ¿humo o realidad?: Python como motor para la generación automática de dashboards y visualizaciones de datos | Pasaría del sábado a las 10:55 al domingo a las 10:55 | A
Minority Report en Londres: Un análisis de las consecuencias del sesgo en la policía predictiva | Pasaría del domingo a las 10:55 al sábado a las 10:55 | A

_Tengo tres cambios más pendientes de confirmación_

**Comment by sdelquin** [comment]
Segundo cambio confirmado:

Charla | Horario | Bloque
-- | -- | --
Mapeando fenología desde el cielo | Pasaría del domingo a las 9:45 al sábado a las 12:55 | B
Como compartir grandes Datasets entre procesos sin perder la salud mental | Pasaría del sábado a las 12:55 al domingo a las 9:45 | B

**Comment by sdelquin** [comment]
Tercer cambio confirmado:

Charla | Horario | Bloque
-- | -- | --
Interpretación de modelos de clasificación usando Python:  abriendo la caja  negra usando SHAP en física de partículas. | Pasaría del sábado a las 10:20 al sábado a las 13:30 | B
Psicología Social y Machine Learning: un futuro ético | Pasaría del sábado a las 13:30 al sábado a las 10:20 | B

**Comment by cmaureir** [comment]
Cambios aplicados en: https://github.com/python-spain/pycones2021-web/pull/57
(Cuidado que el archivo tenía muchos saltos de línea de Windows '\r' y los reemplacé también)

**Comment by sdelquin** [comment]
A qué archivo te refieres?

**Comment by sdelquin** [comment]
Yo no utilizo Windows

**Comment by cmaureir** [comment]
El template tenía muchos archivos 
```
HTML document, Unicode text, UTF-8 text, with very long lines (587), with CRLF line terminators
```
Por eso a veces me salían modificaciones de todas las líneas relacionadas al caracter `^M`
Solo comentaba que lo noté y en ese PR hice los cambios, no era que tu los habías hecho :P

**Comment by sdelquin** [comment]
Ok! Entendido

**Comment by sdelquin** [comment]
Sólo me queda pendiente un posible cambio de horario de la charla "Creating a well-being data layer using machine learning, satellite imagery and ground-truth data" TERCER DÍA; Domingo 3 De Octubre; BLOQUE A
