### ISSUE TITLE
Info para Asamblea Extraordinaria

### ISSUE THREAD

**Issue by sdelquin** [python-spain/pycones2021-web#70]
Quizás se podría añadir algo de información sobre la asamblea extraordinaria que se vea con el botón "Lee más":

![image](https://user-images.githubusercontent.com/1591599/133910570-722455f4-b6ea-48d3-84ab-c45e88f9de34.png)

cc/ @dukebody

**Comment by cmaureir** [comment]
@dukebody  quizás tienen algún párrafo que podamos agregar?

**Comment by dukebody** [comment]
Podemos poner:

> El sábado 2 de octubre de 2021 a las 18:30 en primera convocatoria y a las 19:00 en segunda convocatoria (hora peninsular) se celebrará la Asamblea Extraordinaria de la Asociación. Como viene siendo habitual, la asamblea extraordinaria se celebrará al finalizar la primera jornada de la PyConES 2021.
> 
> Para el comienzo y amenizar la espera entre la primera y segunda convocatoria, prepararemos alguna sorpresa y puede que hasta podáis ganar algún premio. Así que ¡sed puntuales!

No obstante, en principio la asamblea no está abierta totalmente a gente que no esté asociada, por lo que para evitar problemas no pondremos el enlace a la llamada en un sitio totalmente abierto como la web. :)

**Comment by sdelquin** [comment]
Fixed by #85
