### ISSUE TITLE
Botón "Lee más" en Keynoters

### ISSUE THREAD

**Issue by sdelquin** [python-spain/pycones2021-web#87]
¿Debería aparecer el botón de "Lee más" en las Keynoters? 🤔 

![image](https://user-images.githubusercontent.com/1591599/134082763-77ba4b8f-d8b5-49d4-82e4-69ddebd18a5a.png)

**Comment by cmaureir** [comment]
Pues la verdad me pareció bien así, pues ellas no tendrán descripción de la charla, entonces la Keynote va más en quienes son las personas.

**Comment by sdelquin** [comment]
Me parece perfecto 👌🏻
