### ISSUE TITLE
Taller Django Girls

### ISSUE THREAD

**Issue by sdelquin** [python-spain/pycones2021-web#89]
Me surge la duda de si el nombre en ambos sitios debería ser el mismo, ¿y cuál debería ser?

![Captura de pantalla 2021-09-20 a las 23 50 11](https://user-images.githubusercontent.com/1591599/134086876-8b4672f7-3076-49dc-a0cc-92e9a75618b1.png)

cc/ @ClaraMS @cmaureir @dukebody

**Comment by cmaureir** [comment]
La razón por la que dejé "Taller Django" ahí es porque:
* Tenemos el logo PyLadies
* por PyLadies Madrid
* Twitter: PyLadiesMadrid
haha entonces era 'pyladies' muchas veces.

El tema es que como el elemento del menú va a la sección de más abajo, quizás no sea mucho problema, pero claro, podemos cambiarlo también para que sean iguales.

No tengo una opinión fuerte, lo dejo a su criterio :)

**Comment by sdelquin** [comment]
También me convenciste 😅 . Así que nada que objetar.
